'''
Create Date: 2025-01-02
Description: Remove each file that is empty. Heavily generated by ChatGPT.

             **NOTE**: To see the output of this script in an `output.txt` file use the command: $ python -u remove_empty_files.py >> output.txt. 
             **NOTE**: To run the procedure in the background, use the command: $ nohup python -u remove_empty_files.py >> output.txt 2>&1 &. This will return a process number such as [1] 66581, which can be used to kill the process.
             Breakdown:
             1. `nohup`: This allows the script to continue running even after you log out or close the terminal.
             2. python -u <file_name>.py: This part is executing your Python script in unbuffered mode (meaning that output is written immediately). If you are using Python 3, you might want to specify python3 instead of just python, depending on your environment.
             3. >> output.txt 2>&1:
                 * >> output.txt appends the standard output (stdout) of the script to output.txt instead of overwriting it.
                 * 2>&1 redirects standard error (stderr) to the same file as standard output, so both stdout and stderr go into output.txt.
             4. &: This runs the command in the background.
'''
import os

from google.cloud import storage


os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/Users/user/ficc/ficc/mitas_creds.json'

STORAGE_CLIENT = storage.Client()

MSRB_DAILY_REPLAY_FILE_BUCKET_NAME = 'msrb_trade_history'


def delete_empty_files(bucket_name: str):
    '''Deletes all empty files (files with size 0 bytes) from the specified GCS bucket.'''
    bucket = STORAGE_CLIENT.bucket(bucket_name)
    blobs = bucket.list_blobs()    # list all files in the bucket

    empty_file_count = 0
    for blob in blobs:
        if blob.size == 0:    # check if the file size is 0 bytes
            print(f'Deleting empty file: {blob.name}')
            blob.delete()
            empty_file_count += 1

    print(f'Deleted {empty_file_count} empty file(s) from the bucket {bucket_name}')


if __name__ == '__main__':
    delete_empty_files(MSRB_DAILY_REPLAY_FILE_BUCKET_NAME)
