// <auto-generated/>
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CustomFields.cs" company="MBS Source">
//   Copyright © 2016 MBS Source. All Rights Reserved.
// </copyright>
// <summary>
//   Defines the CustomFields type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace FixCommon
{
    using System.Globalization;

    /// <summary>The custom fields.</summary>
    public static class CustomFields
    {
        public const int TIMESTAMP_FILED = 5001;
        public const string SOH = "\u0001";

        //traces
        #region trace
        public const string RDID = "RDID";
        public const string QUANTITY_INDICATOR = "QuantityIndicator";
        public const string REPORTING_PARTY_SIDE = "ReportingPartySide";
        public const string AS_OF_INDICATOR = "AsOfIndicator";
        public const string CREATED_DATE = "CreatedDate";
        public const string REPORTING_PARTY_TYPE = "ReportingPartyType";
        public const string CONTRAPARTY_TYPE = "ContraPartyType";
        public const string RDID_DESCRIPTION = "RDIDDescription";
        public const string RAW_FEED_ID = "RawFeedId";
        public const string BSYM = "Bsym";
        public const string UPDATE_DATE = "UpdatedDate";

        public const int RDID_FIELD = 5007;
        public const int QUANTITY_INDICATOR_FIELD = 5008;
        public const int REPORTING_PARTY_SIDE_FIELD = 5009;
        public const int AS_OF_INDICATOR_FIELD = 5010;
        public const int CREATED_DATE_FIELD = 5011;
        public const int BUY_SELL_INDICATOR_FIELD = 5012;
        public const int REPORTING_PARTY_TYPE_FIELD = 5013;
        public const int CONTRAPARTY_TYPE_FIELD = 5014;
        public const int RDID_DESCRIPTION_FIELD = 5015;
        public const int RAW_FEED_ID_FIELD = 5016;
        public const int BSYM_FIELD = 5017;
        public const int UPDATE_DATE_FIELD = 5018;

        public const string MBS_MESSAGE_TYPE = "MbsMessageType";
        public const int MBS_MESSAGE_TYPE_FIELD = 5019;

        public const string SUB_PRODUCT_TYPE = "SubProductType";
        public const int SUB_PRODUCT_TYPE_FIELD = 5020;

        public const string BOND_ID = "BondId";
        public const int BOND_ID_FIELD = 5021;

        public const string FACTOR = "Factor";
        public const int FACTOR_FIELD = 5022;

        public const string SPECIAL_PRICE_INDICATOR = "SpecialPriceIndicator";
        public const int SPECIAL_PRICE_INDICATOR_FIELD = 5023;

        public const string SALE_CONDITION3 = "SaleCondition3";
        public const int SALE_CONDITION3_FIELD = 5024;

        public const string SALE_CONDITION4 = "SaleCondition4";
        public const int SALE_CONDITION4_FIELD = 5025;

        public const string CONTRA_PARTY_TYPE = "ContraPartyType";
        public const int CONTRA_PARTY_TYPE_FIELD = 5026;

        public const string MBSROOT_TRACEID = "MbsRootTraceID";
        public const int MBSROOT_TRACEID_FIELD = 5027;

        public const string IS_CANCELED = "IsCanceled";
        public const int IS_CANCELED_FIELD = 5028;

        public const string BONDIDENTIFIERS = "BondIdentifiers";
        public const int BONDIDENTIFIERS_FIELD = 5029;

        public const string LAST_ID = "LastId";
        public const int LAST_ID_FIELD = 5030;

        public const string EXCHANGE = "Exchange";
        public const int EXCHANGE_FIELD = 7600;

        public const string ORIGINALMESSAGESEQNUMBER = "OriginalMessageSeqNumber";
        public const int ORIGINALMESSAGESEQNUMBER_FIELD = 7601;

        public const string ORIGINALDISSEMINATIONDATE = "OriginalDisseminationDate";
        public const int ORIGINALDISSEMINATIONDATE_FIELD = 7602;        

        public const string HIGHPRICE = "HighPrice";
        public const int HIGHPRICE_FIELD = 7603;

        public const string LOWPRICE = "LowPrice";
        public const int LOWPRICE_FIELD = 7604;

        public const string LASTSALEPRICE = "LastSalePrice";
        public const int LASTSALEPRICE_FIELD = 7605;

        public const string RENUMERATION = "Remuneration";
        public const int RENUMERATION_FIELD = 7606;

        public const string CHANGEINDICATOR = "ChangeIndicator";
        public const int CHANGEINDICATOR_FIELD = 7607;

        public const string ATSINDICATOR = "AtsIndicator";
        public const int ATSINDICATOR_FIELD = 7608;

        public const string FINRA_CREATED_DATE = "FinraCreatedDate";
        public const int FINRA_CREATED_DATE_FIELD = 7614;

        public const string MESSAGESEQNUMBER = "MessageSeqNumber";
        public const int MESSAGESEQNUMBER_FIELD = 7615;

        public const string DISSEMINATIONDATE = "DisseminationDate";
        public const int DISSEMINATIONDATE_FIELD = 7616;

        #endregion  

        public const string DATE_TIME_FORMAT_WITH_MILLISECONDS = "yyyyMMdd-HH:mm:ss.fff";
        public const string DATE_TIME_FORMAT_WITH_MILLISECONDS1 = "MM/dd/yyyy HH:mm:ss.fff";
        public const string DATE_TIME_FORMAT_WITH_MILLISECONDS_SQL = "yyyy-MM-dd HH:mm:ss.fff";
        public const string NULL_DATE = "19000101-00:00:00.000";
        public const string EMPTY_VALUE = "#E#";
        public const string NULL_VALUE = "#N#";
        public const string WHITESPACE_VALUE = "#WS#";
        public const string DATE_TIME_FORMAT_WITHOUT_MILLISECONDS = "yyyyMMdd-HH:mm:ss";
        public const string DATE_ONLY_FORMAT = "yyyyMMdd";
        public const string TIME_ONLY_FORMAT_WITH_MILLISECONDS = "HH:mm:ss.fff";
        public const string TIME_ONLY_FORMAT_WITHOUT_MILLISECONDS = "HH:mm:ss";
        public static string[] DATE_TIME_FORMATS = { "yyyyMMdd-HH:mm:ss.fff", "yyyyMMdd-HH:mm:ss" };
        public static string[] DATE_ONLY_FORMATS = { "yyyyMMdd" };
        public static string[] TIME_ONLY_FORMATS = { "HH:mm:ss.fff", "HH:mm:ss" };
        public static DateTimeStyles DATE_TIME_STYLES = DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal;
        public static CultureInfo DATE_TIME_CULTURE_INFO = CultureInfo.InvariantCulture;



    }
}
