'''
Description: An example API call to the cloud function `large_batch_pricing`.
'''
import requests
import json

from google.oauth2 import service_account


USERNAME = None    # TODO: fill in
PASSWORD = None    # TODO: fill in

CREDS_FILEPATH = '/Users/user/ficc/ficc/mitas_creds.json'
CUSIPS_TO_BE_PRICED_CSV_FILEPATH = 'files/1k.csv'

# Set your Cloud Function details
project_id = 'eng-reactor-287421'
function_name = 'large_batch_pricing'
function_url = f'https://us-central1-{project_id}.cloudfunctions.net/{function_name}'


def get_access_token_from_creds_json(creds_json_filepath=CREDS_FILEPATH):
    '''Get an access token from the creds_json_filepath. Heavily generated by Claude 3 Haiku.
    NOTE: alternate way to get the access token: `app_engine/demo/server/resources.py::sign_in_with_email_and_password(...)`.'''
    # Create credentials from the service account key
    credentials = service_account.Credentials.from_service_account_file(creds_json_filepath,
                                                                        scopes=['https://www.googleapis.com/auth/cloud-platform'])
    return credentials.token


# Set your authentication credentials
access_token = get_access_token_from_creds_json()

# Make the API request
headers = {
    'Content-Type': 'application/json',
    'Authorization': f'Bearer {access_token}'
}

# Prepare the request data
files = dict()
with open(CUSIPS_TO_BE_PRICED_CSV_FILEPATH, 'rb') as file:
    files = {'file': file}
    response = requests.post(function_url, headers=headers, data={'username': USERNAME, 'password': PASSWORD}, files=files)

# Check the response
if response.status_code == 200:
    print('Request successful!')
    print(response.json())
else:
    print(f'Request failed with status code: {response.status_code}')
    print(response.text)
