'''
Description: This script renames the archived models in the Google Cloud bucket: automated_training. 
It was originally used to add the year to the model name (e.g., convert model-08-09 to model-2023-08-09). 
Now, it can be modified to group models into folders for better organization.
'''
import subprocess


DOLLAR_PRICE_MODEL_DATES_2023 = ['08-02', 
                                 '08-09', 
                                 '08-10', 
                                 '08-15', 
                                 '08-16', 
                                 '08-18', 
                                 '08-22', 
                                 '08-23', 
                                 '08-24', 
                                 '08-29', 
                                 '08-31', 
                                 '09-01', 
                                 '09-06', 
                                 '09-08', 
                                 '09-13', 
                                 '09-14', 
                                 '09-15', 
                                 '09-19', 
                                 '09-21', 
                                 '09-22', 
                                 '09-26', 
                                 '09-27', 
                                 '10-05', 
                                 '10-06', 
                                 '10-09', 
                                 '10-13', 
                                 '10-17', 
                                 '10-18', 
                                 '10-24', 
                                 '10-25', 
                                 '10-26', 
                                 '10-27', 
                                 '10-31', 
                                 '11-01', 
                                 '11-02', 
                                 '11-03', 
                                 '11-07', 
                                 '11-08', 
                                 '11-09',
                                # '11-14',
                                #  '11-15',
                                #  '11-17',
                                #  '11-21',
                                #  '11-22',
                                #  '11-23',
                                #  '11-29',
                                #  '11-30',
                                #  '12-04',
                                #  '12-05',
                                #  '12-06',
                                #  '12-07',
                                #  '12-08',
                                #  '12-11',
                                #  '12-12',
                                #  '12-13',
                                #  '12-14',
                                #  '12-15',
                                #  '12-18',
                                #  '12-19',
                                #  '12-20',
                                #  '12-21',
                                #  '12-22',
                                #  '12-25',
                                #  '12-27',
                                #  '12-28',
                                #  '12-29'
                                ]

DOLLAR_PRICE_MODEL_DATES_2024 = [#  '01-11', 
                                #  '01-12', 
                                #  '01-16', 
                                #  '01-17', 
                                #  '01-18', 
                                #  '01-19', 
                                #  '01-23', 
                                #  '01-25', 
                                #  '01-26', 
                                #  '01-29', 
                                #  '01-30', 
                                #  '01-31', 
                                #  '02-01', 
                                #  '02-02', 
                                #  '02-05', 
                                #  '02-06', 
                                #  '02-07', 
                                #  '02-08', 
                                #  '02-09', 
                                #  '02-12', 
                                #  '02-13', 
                                #  '02-14', 
                                #  '02-15', 
                                #  '02-16', 
                                #  '02-19', 
                                #  '02-20', 
                                #  '02-21',
                                #  '02-22',
                                #  '02-23',
                                #  '02-26',
                                #  '02-27',
                                #  '02-28',
                                #  '02-29',
                                #  '03-01',
                                #  '03-04',
                                #  '03-05',
                                #  '03-06',
                                #  '03-07',
                                #  '03-08',
                                #  '03-11',
                                #  '03-12',
                                #  '03-13',
                                #  '03-14',
                                #  '03-15',
                                #  '03-18',
                                #  '03-19',
                                #  '03-20',
                                #  '03-21',
                                #  '03-22',
                                #  '03-25',
                                #  '03-26',
                                #  '03-27',
                                #  '03-28',
                                #  '03-29',
                                #  '04-02',
                                #  '04-03',
                                #  '04-04',
                                #  '04-05',
                                #  '04-08',
                                #  '04-09',
                                #  '04-10',
                                #  '04-11',
                                #  '04-12',
                                #  '04-15',
                                #  '04-16',
                                #  '04-17',
                                #  '04-18',
                                #  '04-19',
                                #  '04-22',
                                #  '04-23',
                                #  '04-24',
                                #  '04-25',
                                #  '04-29',
                                #  '04-30',
                                #  '05-01',
                                #  '05-03',
                                #  '05-17',
                                #  '05-21', 
                                #  '05-23',
                                #  '05-27',
                                #  '05-29',
                                #  '05-30',
                                #  '05-31',
                                #  '06-04',
                                #  '06-05',
                                #  '06-06'
                                ]

DOLLAR_PRICE_MODEL_DATES_2024_INACCURATE = ['04-26',
                                            '05-02',
                                            '05-06',
                                            '05-07',
                                            '05-08',
                                            '05-09',
                                            '05-10',
                                            '05-13',
                                            '05-14',
                                            '05-15',
                                            '05-16',
                                            '05-20',
                                            '05-22',
                                            '05-24',
                                            '06-03',
                                            '06-07']

YIELD_SPREAD_MODEL_DATES_2023 = [
                                #  '06-21', 
                                #  '06-23', 
                                #  '06-26', 
                                #  '06-28', 
                                #  '07-12', 
                                #  '07-21', 
                                #  '07-23', 
                                #  '07-26', 
                                #  '07-27', 
                                #  '07-28', 
                                #  '07-31', 
                                #  '08-01', 
                                #  '08-03', 
                                #  '08-04', 
                                #  '08-07', 
                                #  '08-08', 
                                 '08-09', 
                                #  '08-10', 
                                #  '08-14', 
                                #  '08-15', 
                                #  '08-16', 
                                #  '08-17', 
                                #  '08-18', 
                                #  '08-23', 
                                #  '08-24', 
                                #  '08-25', 
                                #  '08-28', 
                                #  '08-29', 
                                #  '08-31', 
                                #  '09-01', 
                                #  '09-04', 
                                #  '09-06', 
                                #  '09-07', 
                                #  '09-08', 
                                #  '09-12', 
                                #  '09-13', 
                                #  '09-14', 
                                #  '09-15', 
                                #  '09-18', 
                                #  '09-19', 
                                #  '09-20', 
                                #  '09-21', 
                                #  '09-22', 
                                #  '09-25', 
                                #  '09-26', 
                                #  '09-27', 
                                #  '09-28', 
                                #  '09-29', 
                                #  '09-30', 
                                #  '10-03', 
                                #  '10-04', 
                                #  '10-05', 
                                #  '10-06', 
                                #  '10-09', 
                                #  '10-11', 
                                #  '10-12', 
                                #  '10-13', 
                                #  '10-16', 
                                #  '10-17', 
                                #  '10-18', 
                                #  '10-19', 
                                #  '10-20', 
                                #  '10-23', 
                                #  '10-24', 
                                #  '10-25', 
                                #  '10-26', 
                                #  '10-27', 
                                #  '10-30', 
                                #  '10-31', 
                                #  '11-01', 
                                #  '11-02', 
                                #  '11-03', 
                                #  '11-07', 
                                #  '11-08', 
                                #  '11-09',
                                #  '11-10',
                                #  '11-13',
                                #  '11-14',
                                #  '11-15',
                                #  '11-16',
                                #  '11-17',
                                #  '11-20',
                                #  '11-21',
                                #  '11-22',
                                #  '11-23',
                                #  '11-27',
                                #  '11-28',
                                #  '11-29',
                                #  '11-30',
                                #  '12-01',
                                #  '12-04',
                                #  '12-05',
                                #  '12-06',
                                #  '12-07',
                                #  '12-08',
                                #  '12-11',
                                #  '12-12',
                                #  '12-13',
                                #  '12-14',
                                #  '12-15',
                                #  '12-18',
                                #  '12-19',
                                #  '12-20',
                                #  '12-21',
                                #  '12-22',
                                #  '12-25',
                                #  '12-27',
                                #  '12-28',
                                #  '12-29'
                                 ]

YIELD_SPREAD_MODEL_DATES_2024 = ['01-01',
                                  '01-03',
                                  '01-04',
                                  '01-05',
                                  '01-08',
                                  '01-09',
                                  '01-10',
                                  '01-11',
                                  '01-16',
                                  '01-17',
                                  '01-18',
                                  '01-19',
                                  '01-12',
                                  '01-23',
                                  '01-24',
                                  '01-25',
                                  '01-26',
                                  '01-29',
                                  '01-30',
                                  '01-31',
                                  '02-01',
                                  '02-02',
                                  '02-05',
                                  '02-06',
                                  '02-07',
                                  '02-08',
                                  '02-09',
                                  '02-12',
                                  '02-13',
                                  '02-14',
                                  '02-15',
                                  '02-16',
                                  '02-19',
                                  '02-20',
                                  '02-21',
                                  '02-22',
                                  '02-23',
                                  '02-26',
                                  '02-27',
                                  '02-28',
                                  '02-29',
                                  '03-01',
                                  '03-04',
                                  '03-05',
                                  '03-06',
                                  '03-07',
                                  '03-08',
                                  '03-11',
                                  '03-12',
                                  '03-13',
                                  '03-14',
                                  '03-15',
                                  '03-18',
                                  '03-19',
                                  '03-20',
                                  '03-21',
                                  '03-22',
                                  '03-25',
                                  '03-26',
                                  '03-27',
                                  '03-28',
                                  '03-29',
                                  '04-02',
                                  '04-03',
                                  '04-04',
                                  '04-05',
                                  '04-08',
                                  '04-09',
                                  '04-10',
                                  '04-11',
                                  '04-12',
                                  '04-15',
                                  '04-17',
                                  '04-18',
                                  '04-19',
                                  '04-22',
                                  '04-23',
                                  '04-24',
                                  '04-26',
                                  '04-29',
                                  '05-01',
                                  '05-03',
                                  '05-09',
                                  '05-10',
                                  '05-13',
                                  '05-14',
                                  '05-23',
                                  '05-24',
                                  '05-27',
                                  '05-29',
                                  '05-30',
                                  '06-03',
                                  '06-05',
                                  '06-06',
                                  '06-07']

YIELD_SPREAD_MODEL_DATES_2024_INACCURATE = ['04-25', 
                                            '04-30', 
                                            '05-02',
                                            '05-06',
                                            '05-07',
                                            '05-08',
                                            '05-15',
                                            '05-16',
                                            '05-17',
                                            '05-20',
                                            '05-21',
                                            '05-22',
                                            '05-31',
                                            '06-04']

SIMILAR_TRADES_MODEL_DATES_2024 = ['04-25',
                                   '04-26',
                                   '04-29',
                                   '05-01',
                                   '05-02',
                                   '05-03',
                                   '05-06',
                                   '05-10',
                                   '05-21',
                                   '05-22',
                                   '05-24',
                                   '05-27',
                                   '05-29',
                                   '05-30',
                                   '06-03',
                                   '06-05',
                                   '06-06']

SIMILAR_TRADES_MODEL_DATES_2024_INACCURATE = ['04-30',
                                              '05-07',
                                              '05-08',
                                              '05-09',
                                              '05-13',
                                              '05-14',
                                              '05-15',
                                              '05-16',
                                              '05-17',
                                              '05-20',
                                              '05-23',
                                              '05-31',
                                              '06-04',
                                              '06-07']


def run_command(command):
    try:
        # Execute the command
        result = subprocess.run(command, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        # Print the output
        print("Output:\n", result.stdout)
        if result.stderr:
            print("Errors:\n", result.stderr)
    except subprocess.CalledProcessError as e:
        print(f"An error occurred: {e}")


def rename_dollar_price_model_command(date_wo_year, year=2024):
    return f'gsutil mv gs://automated_training/dollar-model-{date_wo_year} gs://automated_training/dollar-model-{year}-{date_wo_year}'


def rename_dollar_price_model_inaccurate_command(date_wo_year, year=2024):
    return f'gsutil mv gs://automated_training/dollar_price_model_inaccurate/dollar-model-{date_wo_year} gs://automated_training/dollar_price_model_inaccurate/dollar-model-{year}-{date_wo_year}'


def rename_yield_spread_model_command(date_wo_year, year=2024):
    return f'gsutil mv gs://automated_training/yield_spread_model/model-{date_wo_year} gs://automated_training/yield_spread_model/model-{year}-{date_wo_year}'


def rename_yield_spread_model_inaccurate_command(date_wo_year, year=2024):
    return f'gsutil mv gs://automated_training/yield_spread_model_inaccurate/model-{date_wo_year} gs://automated_training/yield_spread_model_inaccurate/model-{year}-{date_wo_year}'


def rename_similar_trades_model_command(date_wo_year, year=2024):
    return f'gsutil mv gs://automated_training/similar-trades-model-{date_wo_year} gs://automated_training/similar-trades-model-{year}-{date_wo_year}'


def rename_similar_trades_model_inaccurate_command(date_wo_year, year=2024):
    return f'gsutil mv gs://automated_training/similar_trades_model_inaccurate/similar-trades-model-{date_wo_year} gs://automated_training/similar_trades_model_inaccurate/similar-trades-model-{year}-{date_wo_year}'


if __name__ == "__main__":
    # for date in DOLLAR_PRICE_MODEL_DATES_2024:
    #     run_command(rename_dollar_price_model_command(date, 2024))
    # for date in DOLLAR_PRICE_MODEL_DATES_2023:
    #     run_command(rename_dollar_price_model_command(date, 2023))
    # for date in YIELD_SPREAD_MODEL_DATES_2024:
    #     run_command(rename_yield_spread_model_command(date, 2024))
    for date in YIELD_SPREAD_MODEL_DATES_2023:
        run_command(rename_yield_spread_model_command(date, 2023))
    # for date in SIMILAR_TRADES_MODEL_DATES_2024:
    #     run_command(rename_similar_trades_model_command(date, 2024))
    # for date in YIELD_SPREAD_MODEL_DATES_2024_INACCURATE:
    #     run_command(rename_yield_spread_model_inaccurate_command(date, 2024))
    # for date in DOLLAR_PRICE_MODEL_DATES_2024_INACCURATE:
    #     run_command(rename_dollar_price_model_inaccurate_command(date, 2024))
    # for date in SIMILAR_TRADES_MODEL_DATES_2024_INACCURATE:
    #     run_command(rename_similar_trades_model_inaccurate_command(date, 2024))
