runtime: python37

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301