-- single_cusip_query.sql - Gil - 2025-09-28: TODO: Change to Redis

WITH latest_cusip_data AS (
  SELECT 
      cusip,
      ROW_NUMBER() OVER (
        PARTITION BY cusip 
        ORDER BY 
          ref_valid_from_date DESC NULLS LAST,
          file_received_from_provider_timestamp DESC NULLS LAST
      ) AS rn,
      -- reference fields
      delivery_date,
      coupon,
      coupon_type,
      maturity_date,
      issue_price,
      issue_amount,
      maturity_amount,
      orig_principal_amount,
      original_yield,
      is_callable,
      is_called,
      callable_at_cav,
      next_call_date,
      next_call_price,
      par_call_date,
      par_call_price,
      called_redemption_type,
      call_timing,
      call_timing_in_part,
      sp_long,
      incorporated_state_code,
      state_tax_status,
      federal_tax_status,
      purpose_class,
      purpose_sub_class,
      use_of_proceeds,
      muni_security_type,
      muni_issue_type,
      capital_type,
      series_name,
      min_amount_outstanding,
      max_amount_outstanding,
      next_sink_date,
      has_sink_schedule,
      sink_frequency,
      sink_amount_type,
      other_enhancement_type,
      has_unexpired_lines_of_credit,
      years_to_loc_expiration,
      is_escrowed_or_pre_refunded,
      default_exists,
      make_whole_call,
      extraordinary_make_whole_call,
      is_general_obligation,
      refund_date,
      interest_payment_frequency,
      accrual_date,
      previous_coupon_payment_date,
      next_coupon_payment_date,
      first_coupon_date,
      last_period_accrues_from_date,
      par_price
  FROM `eng-reactor-287421.reference_data_v2.reference_data_flat`
  WHERE cusip = @cusip
)
SELECT 
    cusip,

    -- trade-specific fields we override via parameters
    @par_traded        AS par_traded,        -- e.g., 100 or 1000
    CURRENT_DATE("US/Eastern")    AS trade_date,
    CURRENT_DATETIME("US/Eastern") AS trade_datetime,
    CURRENT_DATE("US/Eastern")    AS settlement_date,
    delivery_date,
    @trade_type        AS trade_type,        -- 'S' | 'P' | 'D'
    "I"                AS transaction_type,  -- default from your example

    -- reference fields (plus rating alias)
    coupon,
    coupon_type,
    maturity_date,
    issue_price,
    issue_amount,
    maturity_amount,
    orig_principal_amount,
    original_yield,
    is_callable,
    is_called,
    callable_at_cav,
    next_call_date,
    next_call_price,
    par_call_date,
    par_call_price,
    called_redemption_type,
    call_timing,
    call_timing_in_part,
    sp_long AS rating,
    incorporated_state_code,
    state_tax_status,
    federal_tax_status,
    purpose_class,
    purpose_sub_class,
    use_of_proceeds,
    muni_security_type,
    muni_issue_type,
    capital_type,
    series_name,
    min_amount_outstanding,
    max_amount_outstanding,
    next_sink_date,
    has_sink_schedule,
    sink_frequency,
    sink_amount_type,
    other_enhancement_type,
    has_unexpired_lines_of_credit,
    years_to_loc_expiration,
    is_escrowed_or_pre_refunded,
    default_exists,
    make_whole_call,
    extraordinary_make_whole_call,
    FALSE AS is_non_transaction_based_compensation,
    is_general_obligation,
    refund_date,
    interest_payment_frequency,
    accrual_date,
    accrual_date AS dated_date,
    previous_coupon_payment_date,
    next_coupon_payment_date,
    first_coupon_date,
    last_period_accrues_from_date,
    par_price
FROM latest_cusip_data
WHERE rn = 1
